version: '3.8'

services:
  app:
    image: lam151251/proxy-war:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/proxywar
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
