services:
  mongo:
    image: mongo:latest
    container_name: proxy_war_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Proxy_War

  app:
    image: proxy-war:latest
    container_name: proxy_war_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/Proxy_War
      PORT: 8080

volumes:
  mongo_data: